#ifndef INCLUDE_KEYBOARD_H
#define INCLUDE_KEYBOARD_H
#include "interrupt.h"
void keyboard_handler(struct cpu_state * r);
void init_keyboard();
char getc();
typedef enum 
{
	KEY_SPACE 			=	' ',
	KEY_0				=	'0',
	KEY_1				=	'1',
	KEY_2				=	'2',
	KEY_3				=	'3',
	KEY_4				=	'4',
	KEY_5				=	'5',
	KEY_6				=	'6',
	KEY_7				=	'7',
	KEY_8				=	'8',
	KEY_9				=	'9',

	KEY_A				=	'a',
	KEY_B				=	'b',
	KEY_C				=	'c',
	KEY_D				=	'd',
	KEY_E				=	'e',
	KEY_F				=	'f',
	KEY_G				=	'g',
	KEY_H				=	'h',
	KEY_I				=	'i',
	KEY_J				=	'j',
	KEY_K				=	'k',
	KEY_L				=	'l',
	KEY_M				=	'm',
	KEY_N				=	'n',
	KEY_O				=	'o',
	KEY_P				=	'p',
	KEY_Q				=	'q',
	KEY_R				=	'r',
	KEY_S				=	's',
	KEY_T				=	't',
	KEY_U				=	'u',
	KEY_V				=	'v',
	KEY_W				=	'w',
	KEY_X				=	'x',
	KEY_Y				=	'y',
	KEY_Z				=	'z',

	KEY_DOT				=	'.',
	KEY_COMMA			=	',',	
	KEY_COLON			=	':',	
	KEY_SEMICOLON		=	';',		
	KEY_SLASH			=	'/',	
	KEY_BACKSLASH		=	'\\',		
	KEY_PLUS			=	'+',	
	KEY_MINUS			=	'-',	
	KEY_ASTERISK		=	'*',		
	KEY_EXCLAMATION		=	'!',		
	KEY_QUESTION		=	'?',		
	KEY_QUOTEDOUBLE		=	'"',		
	KEY_QUOTE			=	'\'',	
	KEY_EQUAL			=	'=',	
	KEY_HASH			=	'#',	
	KEY_PERCENT			=	'%',	
	KEY_AMPERSAND		=	'&',		
	KEY_UNDERSCORE		=	'_',		
	KEY_LEFTPAREN		=	'(',		
	KEY_RIGHTPAREN		=	')',		
	KEY_LEFTBRACKET		=	'[',		
	KEY_RIGHTBRACKET	=	']',			
	KEY_LEFTCURL		=	'{',		
	KEY_RIGHTCURL		=	'}',		
	KEY_LESS			=	'<',	
	KEY_GREATER			=	'>',	
	KEY_PIPE			=	'|',	
	KEY_GRAVE			=	'`',	
	KEY_TILDE			=	'~',	
	KEY_AT				=	'@',
	KEY_CARAT			=	'^',	
		
	KEY_RETURN			=	'\n',	
	KEY_ESCAPE			=	0x1B,	
	KEY_BACKSPACE		=	0x08,		
	KEY_UP				=	0x1C,
	KEY_DOWN			=	0x1D,	
	KEY_LEFT			=	0x1E,	
	KEY_RIGHT			=	0x1F,	
	KEY_TAB				=	0x09,
	KEY_CAPSLOCK		=	0x1001,		
	KEY_LSHIFT			=	0x1002,
	KEY_RSHIFT			=	0x1003,
	KEY_F1				=	0X1004,
	KEY_F2				=	0X1005,
	KEY_F3				=	0X1006,
	KEY_F4				=	0X1007,
	KEY_F5				=	0X1008,
	KEY_F6				=	0X1009,
	KEY_F7				=	0X100A,
	KEY_F8				=	0X100B,
	KEY_F9				=	0X100C,
	KEY_F10				=	0X100D,
	KEY_F11				=	0X100E,
	KEY_F12				=	0X100F,
	KEY_NUMLOCK			=	0x1010,
	KEY_PGUP			=	0x1011,
	KEY_END				=	0x1012,
	KEY_INSERT			=	0x1013,
	KEY_DELETE			=	0x1014,
	KEY_SCROLL_LOCK		=	0x1015,

	KEY_UNKNOWN			=	0xFFFF,
				
} KEYCODE;
#endif